const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const body=document.body, nav=$('#nav');
$('#menuBtn').addEventListener('click',()=>nav.classList.toggle('open'));
$$('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const saved=localStorage.getItem('fahima-theme'); if(saved==='dark') body.classList.add('dark');
$('#themeToggle').textContent=body.classList.contains('dark')?'☀':'☾';
$('#themeToggle').addEventListener('click',()=>{body.classList.toggle('dark');localStorage.setItem('fahima-theme',body.classList.contains('dark')?'dark':'light');$('#themeToggle').textContent=body.classList.contains('dark')?'☀':'☾'});
window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('.scroll-line').style.width=(scrollY/h*100)+'%';let current='home';$$('section[id]').forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current));});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));
window.addEventListener('pointermove',e=>{$('.cursor-glow').style.left=e.clientX+'px';$('.cursor-glow').style.top=e.clientY+'px'});
const data={
saigai:{tag:'WEB · ACCESSIBILITY',title:'Saigai',desc:'An ISL-based Communication Web Application built around Indian Sign Language data. The current implementation recognizes single words from uploaded sign-language content and supports webcam interaction and speech output.',tech:['Python 3.13.3','Flask','HTML5','CSS3','JavaScript','MediaPipe Tasks Vision','OpenCV','NumPy','scikit-learn','SQLite','Web Speech API','WebRTC','Jinja2','Zenodo ISL dataset'],points:['Uses real Indian Sign Language dataset data from Zenodo; current training uses a 1.3 GB subset of the larger dataset.','Users select a language during sign in/login and can upload sign-language content for recognition.','Current recognition focuses on individual words; unseen videos are around 60%+ while the exact training video can reach 100%.','Roadmap includes improved generalization, complete sentence recognition, accessible chatbot interaction and speech/text-to-sign communication.']},
lablens:{tag:'PRACTICAL LAB PLATFORM',title:'LabLens Edge',desc:'A web application for practical laboratory learning and assessment. Students access instructor-posted projects, follow procedures, record their work, take coded exams and receive results after instructor grading.',tech:['Python','Flask','HTML5','CSS3','JavaScript','OpenCV','Webcam / MediaDevices API','MediaRecorder API','SQLite','ONNX','Qualcomm AI / Snapdragon NPU'],points:['Admins or instructors can create projects with names, descriptions, steps and duration.','Students can access guided practical work and automatically send recorded video to the admin.','Exams use an examination code; during an exam the webcam opens and the procedure is hidden so students implement independently.','Admin and student histories are maintained, with student name, email and submitted video available for review.','Snapdragon NPU optimization is a planned target for on-device AI inference.']},
dustbin:{tag:'IOT',title:'IoT Smart Dustbin',desc:'A sensor-based smart dustbin prototype designed around automatic lid movement.',tech:['Arduino UNO','Ultrasonic Sensor','Servo Motor','Arduino IDE'],points:['Ultrasonic sensing is used to detect proximity.','Arduino UNO controls the prototype logic.','A servo motor drives the dustbin lid mechanism.']},
soil:{tag:'IOT · MONITORING',title:'Soil Moisture Monitoring',desc:'A monitoring system that measures soil moisture and presents the collected data through ThingSpeak.',tech:['Arduino UNO','Soil Moisture Sensor','ThingSpeak','Python','Arduino IDE'],points:['Reads soil moisture through a dedicated sensor.','Uses Arduino UNO and Arduino IDE for the embedded side.','ThingSpeak is used to display the collected monitoring data.']},
temperature:{tag:'IOT · SENSOR SYSTEM',title:'Temperature & Humidity Monitoring',desc:'A DHT11-based monitoring system using Arduino UNO, Python and Wi-Fi connectivity, with the interface accessible through a mobile or laptop browser.',tech:['DHT11','Arduino UNO','Arduino IDE','Python','Wi-Fi'],points:['DHT11 provides temperature and humidity readings.','Python creates/serves the local interface.','The interface can be accessed from a mobile or laptop browser using the localhost address.']}};
const modal=$('#modal');
$$('.project-card').forEach(card=>card.addEventListener('click',e=>{const d=data[card.dataset.project];if(!d)return;$('#modalKicker').textContent=d.tag;$('#modalTitle').textContent=d.title;$('#modalDesc').textContent=d.desc;$('#modalTech').innerHTML=d.tech.map(x=>`<i>${x}</i>`).join('');$('#modalPoints').innerHTML=d.points.map(x=>`<li>${x}</li>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
function close(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}$('#closeModal').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
